export const publicFiles = [
  "404.html",
  "accom.html",
  "activity.html",
  "archive.html",
  "calendar.html",
  "contact.html",
  "data/listings_accom.json",
  "data/listings_do.json",
  "data/listings_food.json",
  "data/listings_other.json",
  "data/archive-index.json",
  "data/site-version.json",
  "favicon.ico",
  "food.html",
  "images/background-01.webp",
  "images/background-02.webp",
  "images/background-03.webp",
  "images/background-04.webp",
  "images/background-05.webp",
  "images/background-06.webp",
  "images/logo145x100.webp",
  "images/og-hero.jpg",
  "images/oze-logo216x100.webp",
  "index.html",
  "llms.txt",
  "robots.txt",
  "site.webmanifest",
  "sitemap.xml",
];

export const publicDirectories = ["assets"];
