// Files copied verbatim into the build. Pages are generated by Astro and are
// not listed here.
export const publicFiles = [
  "data/listings_accom.json",
  "data/listings_do.json",
  "data/listings_food.json",
  "data/listings_community.json",
  "data/listings_services.json",
  "data/archive-index.json",
  "data/site-version.json",
  "favicon.ico",
  "images/background-01.webp",
  "images/background-02.webp",
  "images/background-03.webp",
  "images/background-04.webp",
  "images/background-05.webp",
  "images/background-06.webp",
  "images/logo145x100.webp",
  // No page points at this any more — every page has a card of its own under
  // images/og. It keeps shipping because links shared before that change named
  // it, and a scraper that refetches one should not find a 404 where the
  // picture was.
  "images/og-hero.jpg",
  "images/oze-logo216x100.webp",
  "robots.txt",
  "site.webmanifest",
];

// Cover photographs and share cards are per-week and per-page, so these
// directories ship whole rather than being listed file by file. images/og holds
// the 1200 x 630 Open Graph cards built by tools/build-og.mjs.
export const publicDirectories = [
  "assets",
  "images/covers",
  "images/articles",
  "images/bank",
  "images/listings",
  "images/og",
  "data/directory",
];
